### ISSUE TITLE
Add an lgt8f328p hex compiled file

### ISSUE THREAD

**Issue by IoT64** [ikorb/tapecart#8]
Can you add an lgt8f328p hex compiled file? It will be useful.

**Comment by ikorb** [comment]
WTF is an lgt8f328p?

**Comment by IoT64** [comment]
> WTF is an lgt8f328p?

A clone of ATMEGA328P.

https://github.com/dbuezas/lgt8fx
https://github.com/RalphBacon/LGT8F328P-Arduino-Clone-Chip-ATMega328P
https://wolles-elektronikkiste.de/en/minievb-boards-an-overview

**Comment by ikorb** [comment]
That chip is not pinout-compatible with the hardware in this repository, so just a .hex file would not be sufficient. The chip does not seem to be available from any reputable distributor either and there is no official english-language datasheet for it, so I don't see why I should put in the effort and money to redesign the hardware and port the software over.

If you want it, you'll have to do it yourself.

**Comment by IoT64** [comment]
> That chip is not pinout-compatible with the hardware in this repository, so just a .hex file would not be sufficient. The chip does not seem to be available from any reputable distributor either and there is no official english-language datasheet for it, so I don't see why I should put in the effort and money to redesign the hardware and port the software over.
> 
> If you want it, you'll have to do it yourself.

It is pin compatible (mini pro is), you don't need to redesign pcb only recompile with the correct hardware. Sorry but i ask it because i am not expert with GCC. If you wan't no problem, you aren't obligade. Thank you.

**Comment by ikorb** [comment]
None of the links you provided shows a 14-pin DIL package at all and just from the part number it is clear that the chip is not even intended to be 1:1-replacement compatible with an ATtiny44. Furthermore, some of the links mention that the instruction timing is different, so the cycle-counted assembly code would require modifications to send data with the correct timing. This is absolutely not a "just recompile and it works" thing.

**Comment by IoT64** [comment]
Sorry. Wrong github page. Please excuse me. I'm referring to another tapecart project, that uses your project.
[(https://github.com/KimJorgensen/tapecart)]
Sorry again for my mistake!
